name: test

on:
  pull_request:
  push:
    branches:
      - master
      - release/**
  issue_comment:
    types: [created, edited]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Check if organization member
        uses: JamesSingleton/is-organization-member@main
        id: checkMember
        with:
          username: ${{ github.actor }}
          organization: crypto-org-chain
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: comment-actions
        if: github.event_name == 'issue_comment' && github.event.comment.body == '/runsim' && ${{ steps.checkMember.outputs.result == true }}
        run: echo 'you are allowed to run sim'
      - name: comment-actions
        if: github.event_name == 'issue_comment' && github.event.comment.body == '/runsim' && ${{ steps.checkMember.outputs.result == false }}
        run: echo 'not allowed'

